### ISSUE TITLE
Definir Tema do Projeto

### ISSUE THREAD

**Issue by Bruno-Felix** [DS-AmareloGirassol/AmareloGirassol-Docs#1]
### Descrição
Issue destinada para o levantamento de todas as ideias pensadas e para a escolhe do tema definitivo do projeto.

### Tarefas
- [x] Detalhar nos conmentários todas as ideias propostas;

### Critérios de Aceitação
- [x] Todos os integrantes do grupo concordarem com o tema definido.

**Comment by CamilaSilvaC** [comment]
Rede Social Unb 

-Monte o seu fluxo, com perpectiva de quando você vai se formar, opções de agrupar materia por dificuldade 
-Indicação de boa optativas e atividades 
-Saber se o amigo está aula
-Feedback de professores em cada materia com os motivos
-Perfils oficiais, como de atleticas 
-Forum para grupos bem especificos 
Ex. Meninas nas engenharias, engenheiros com dupla graduação...
Votação para novos foruns 
-Notificação de datas importante, ex. data para o último dia do auxilio.
