### ISSUE TITLE
[US1] Eu, como usuário, gostaria de poder fazer o Cadastro no site

### ISSUE THREAD

**Issue by Bruno-Felix** [DS-AmareloGirassol/AmareloGirassol-Docs#33]

**Comment by Brwnds** [comment]
## Front end - Cadastro
Descrição da Tarefa
Realizar Front end;

 ## Requisitos
A quais requisitos do projeto esta tarefa se refere?

[US1] Eu, como usuário, gostaria de poder fazer o Cadastro no site

 ## Informações Adicionais
![Screenshot from 2024-06-15 11-49-28](https://github.com/DS-AmareloGirassol/AmareloGirassol-Docs/assets/121124773/5dc75eab-fba6-48c2-ad1b-0a5c8e9a55ff)
