### ISSUE TITLE
Levantar Plano de Comunicação e Quadro de Disponibilidade

### ISSUE THREAD

**Issue by Bruno-Felix** [DS-AmareloGirassol/AmareloGirassol-Docs#4]
### Descrição
Issue destinada ao Levantamento do Quadro de Disponibilidade dos integrantes do grupo.

### Tarefas
- [ ] Desenvolver plano de comunicação, ferramentas, horários e reuniões fixas.
- [ ] Todos os integrantes preencherem sua Disponibilidade para reunião/ trabalho no projeto.

### Critérios de Aceitação
- [ ] Plano de Comunicação estar devidamente escrito e inserido na gitpage;
- [ ] Quadro de Disponibilidade de todos os integrantes estar devidamente definido.

**Comment by Bruno-Felix** [comment]
Exemplo de plano_de_comunicacao: [plano_de_comunicacao](https://fga-eps-mds.github.io/2022-1-PUMA-Doc/projeto/plano_de_comunicacao/)

**Comment by Brwnds** [comment]
# Planejamento de Ferramentas
Metodologias ativas/métodos de organização

- Desenvolvimento Front-end:

- Frameworks que serão utilizados para a interface do usuário: 

# Estilização: CSS

- Biblioteca de Estado: 

- Desenvolvimento Back-end:

- Linguagem de Programação (Desenvolvimento do servidor): 

- Banco de Dados: 

- Autenticação: 

- Ferramentas Adicionais:

- APIs de Notificação: 

- Sistema de Votação: 

- Fórum: 

# Funcionalidades e Recursos:

1. Monte o seu fluxo acadêmico:
Interface de Arrastar e Soltar: Permitir que os alunos organizem suas disciplinas por semestre e dificuldade.
Integração com o Sistema Acadêmico: Importar automaticamente as disciplinas e informações do aluno.

2. Indicação de boas optativas e atividades:
Sistema de Recomendação: Algoritmo que sugere optativas e atividades com base no perfil acadêmico do aluno.

3. Saber se o amigo está em aula:
Status de Presença: Permitir que os usuários atualizem seu status de presença em aulas e visualizem o status dos amigos.

4. Feedback de professores:
Sistema de Avaliação: Permitir que os alunos avaliem as disciplinas e a metodologia dos professores.

5. Perfis oficiais:
Páginas de Atléticas e Grupos: Criar perfis oficiais para atléticas, grupos de estudo e organizações estudantis.

6. Fóruns para grupos específicos:
Categorias de Fórum: Criar fóruns segmentados por grupos específicos, como "Meninas nas Engenharias" e "Engenheiros com Dupla Graduação".

7. Notificações de datas importantes:
Agendamento de Notificações: Implementar um sistema de notificações para alertar os usuários sobre datas importantes, como o último dia para solicitar auxílios e benefícios.

# Cronograma de Desenvolvimento:  (sujeito a alteração)
Fase 1 - Planejamento e Design: 1 mês  
Fase 2 - Desenvolvimento Front-end: 2 meses  
Fase 3 - Desenvolvimento Back-end: 2 meses  
Fase 4 - Testes e Implementação: 1 mês  
Fase 5 - Lançamento e Feedback: 1 mês 
Este é um planejamento inicial e pode ser adaptado conforme as necessidades e recursos disponíveis. O envolvimento dos stakeholders é crucial para o sucesso e a relevância da "Rede Social UnB" -  (sujeito a alteração).
